/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../../../../common";
import type {
  OwnedUpgradeabilityStorage,
  OwnedUpgradeabilityStorageInterface,
} from "../../../../contracts/registry/proxy/OwnedUpgradeabilityStorage";

const _abi = [
  {
    inputs: [],
    name: "upgradeabilityOwner",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

const _bytecode =
  "0x6080604052348015600f57600080fd5b5060ae8061001e6000396000f3fe6080604052348015600f57600080fd5b506004361060285760003560e01c80636fde820214602d575b600080fd5b6033605c565b6040805173ffffffffffffffffffffffffffffffffffffffff9092168252519081900360200190f35b60015473ffffffffffffffffffffffffffffffffffffffff169056fea2646970667358221220978c8d5c03e19f00b09485d96e9605dae5543244d0fac33a5b89bd5f3d02552764736f6c63430007050033";

type OwnedUpgradeabilityStorageConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: OwnedUpgradeabilityStorageConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class OwnedUpgradeabilityStorage__factory extends ContractFactory {
  constructor(...args: OwnedUpgradeabilityStorageConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      OwnedUpgradeabilityStorage & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(
    runner: ContractRunner | null
  ): OwnedUpgradeabilityStorage__factory {
    return super.connect(runner) as OwnedUpgradeabilityStorage__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): OwnedUpgradeabilityStorageInterface {
    return new Interface(_abi) as OwnedUpgradeabilityStorageInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): OwnedUpgradeabilityStorage {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as OwnedUpgradeabilityStorage;
  }
}
