/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  ProxyRegistryInterface,
  ProxyRegistryInterfaceInterface,
} from "../../../contracts/registry/ProxyRegistryInterface";

const _abi = [
  {
    inputs: [],
    name: "delegateProxyImplementation",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "owner",
        type: "address",
      },
    ],
    name: "proxies",
    outputs: [
      {
        internalType: "contract OwnableDelegateProxy",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class ProxyRegistryInterface__factory {
  static readonly abi = _abi;
  static createInterface(): ProxyRegistryInterfaceInterface {
    return new Interface(_abi) as ProxyRegistryInterfaceInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): ProxyRegistryInterface {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as ProxyRegistryInterface;
  }
}
