/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface TokenRecipientInterface extends Interface {
  getFunction(nameOrSignature: "receiveApproval"): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "ReceivedEther" | "ReceivedTokens"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "receiveApproval",
    values: [AddressLike, BigNumberish, AddressLike, BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "receiveApproval",
    data: BytesLike
  ): Result;
}

export namespace ReceivedEtherEvent {
  export type InputTuple = [sender: AddressLike, amount: BigNumberish];
  export type OutputTuple = [sender: string, amount: bigint];
  export interface OutputObject {
    sender: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ReceivedTokensEvent {
  export type InputTuple = [
    from: AddressLike,
    value: BigNumberish,
    token: AddressLike,
    extraData: BytesLike
  ];
  export type OutputTuple = [
    from: string,
    value: bigint,
    token: string,
    extraData: string
  ];
  export interface OutputObject {
    from: string;
    value: bigint;
    token: string;
    extraData: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface TokenRecipient extends BaseContract {
  connect(runner?: ContractRunner | null): TokenRecipient;
  waitForDeployment(): Promise<this>;

  interface: TokenRecipientInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  receiveApproval: TypedContractMethod<
    [
      from: AddressLike,
      value: BigNumberish,
      token: AddressLike,
      extraData: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "receiveApproval"
  ): TypedContractMethod<
    [
      from: AddressLike,
      value: BigNumberish,
      token: AddressLike,
      extraData: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "ReceivedEther"
  ): TypedContractEvent<
    ReceivedEtherEvent.InputTuple,
    ReceivedEtherEvent.OutputTuple,
    ReceivedEtherEvent.OutputObject
  >;
  getEvent(
    key: "ReceivedTokens"
  ): TypedContractEvent<
    ReceivedTokensEvent.InputTuple,
    ReceivedTokensEvent.OutputTuple,
    ReceivedTokensEvent.OutputObject
  >;

  filters: {
    "ReceivedEther(address,uint256)": TypedContractEvent<
      ReceivedEtherEvent.InputTuple,
      ReceivedEtherEvent.OutputTuple,
      ReceivedEtherEvent.OutputObject
    >;
    ReceivedEther: TypedContractEvent<
      ReceivedEtherEvent.InputTuple,
      ReceivedEtherEvent.OutputTuple,
      ReceivedEtherEvent.OutputObject
    >;

    "ReceivedTokens(address,uint256,address,bytes)": TypedContractEvent<
      ReceivedTokensEvent.InputTuple,
      ReceivedTokensEvent.OutputTuple,
      ReceivedTokensEvent.OutputObject
    >;
    ReceivedTokens: TypedContractEvent<
      ReceivedTokensEvent.InputTuple,
      ReceivedTokensEvent.OutputTuple,
      ReceivedTokensEvent.OutputObject
    >;
  };
}
