/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface ExchangeCoreInterface extends Interface {
  getFunction(
    nameOrSignature: "approved" | "fills" | "registries"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "OrderApproved"
      | "OrderFillChanged"
      | "OrdersMatched"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "approved",
    values: [AddressLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "fills",
    values: [AddressLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "registries",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(functionFragment: "approved", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "fills", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "registries", data: BytesLike): Result;
}

export namespace OrderApprovedEvent {
  export type InputTuple = [
    hash: BytesLike,
    registry: AddressLike,
    maker: AddressLike,
    staticTarget: AddressLike,
    staticSelector: BytesLike,
    staticExtradata: BytesLike,
    maximumFill: BigNumberish,
    listingTime: BigNumberish,
    expirationTime: BigNumberish,
    salt: BigNumberish,
    orderbookInclusionDesired: boolean
  ];
  export type OutputTuple = [
    hash: string,
    registry: string,
    maker: string,
    staticTarget: string,
    staticSelector: string,
    staticExtradata: string,
    maximumFill: bigint,
    listingTime: bigint,
    expirationTime: bigint,
    salt: bigint,
    orderbookInclusionDesired: boolean
  ];
  export interface OutputObject {
    hash: string;
    registry: string;
    maker: string;
    staticTarget: string;
    staticSelector: string;
    staticExtradata: string;
    maximumFill: bigint;
    listingTime: bigint;
    expirationTime: bigint;
    salt: bigint;
    orderbookInclusionDesired: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OrderFillChangedEvent {
  export type InputTuple = [
    hash: BytesLike,
    maker: AddressLike,
    newFill: BigNumberish
  ];
  export type OutputTuple = [hash: string, maker: string, newFill: bigint];
  export interface OutputObject {
    hash: string;
    maker: string;
    newFill: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OrdersMatchedEvent {
  export type InputTuple = [
    firstHash: BytesLike,
    secondHash: BytesLike,
    firstMaker: AddressLike,
    secondMaker: AddressLike,
    newFirstFill: BigNumberish,
    newSecondFill: BigNumberish,
    metadata: BytesLike
  ];
  export type OutputTuple = [
    firstHash: string,
    secondHash: string,
    firstMaker: string,
    secondMaker: string,
    newFirstFill: bigint,
    newSecondFill: bigint,
    metadata: string
  ];
  export interface OutputObject {
    firstHash: string;
    secondHash: string;
    firstMaker: string;
    secondMaker: string;
    newFirstFill: bigint;
    newSecondFill: bigint;
    metadata: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ExchangeCore extends BaseContract {
  connect(runner?: ContractRunner | null): ExchangeCore;
  waitForDeployment(): Promise<this>;

  interface: ExchangeCoreInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  approved: TypedContractMethod<
    [arg0: AddressLike, arg1: BytesLike],
    [boolean],
    "view"
  >;

  fills: TypedContractMethod<
    [arg0: AddressLike, arg1: BytesLike],
    [bigint],
    "view"
  >;

  registries: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "approved"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BytesLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "fills"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BytesLike],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "registries"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  getEvent(
    key: "OrderApproved"
  ): TypedContractEvent<
    OrderApprovedEvent.InputTuple,
    OrderApprovedEvent.OutputTuple,
    OrderApprovedEvent.OutputObject
  >;
  getEvent(
    key: "OrderFillChanged"
  ): TypedContractEvent<
    OrderFillChangedEvent.InputTuple,
    OrderFillChangedEvent.OutputTuple,
    OrderFillChangedEvent.OutputObject
  >;
  getEvent(
    key: "OrdersMatched"
  ): TypedContractEvent<
    OrdersMatchedEvent.InputTuple,
    OrdersMatchedEvent.OutputTuple,
    OrdersMatchedEvent.OutputObject
  >;

  filters: {
    "OrderApproved(bytes32,address,address,address,bytes4,bytes,uint256,uint256,uint256,uint256,bool)": TypedContractEvent<
      OrderApprovedEvent.InputTuple,
      OrderApprovedEvent.OutputTuple,
      OrderApprovedEvent.OutputObject
    >;
    OrderApproved: TypedContractEvent<
      OrderApprovedEvent.InputTuple,
      OrderApprovedEvent.OutputTuple,
      OrderApprovedEvent.OutputObject
    >;

    "OrderFillChanged(bytes32,address,uint256)": TypedContractEvent<
      OrderFillChangedEvent.InputTuple,
      OrderFillChangedEvent.OutputTuple,
      OrderFillChangedEvent.OutputObject
    >;
    OrderFillChanged: TypedContractEvent<
      OrderFillChangedEvent.InputTuple,
      OrderFillChangedEvent.OutputTuple,
      OrderFillChangedEvent.OutputObject
    >;

    "OrdersMatched(bytes32,bytes32,address,address,uint256,uint256,bytes32)": TypedContractEvent<
      OrdersMatchedEvent.InputTuple,
      OrdersMatchedEvent.OutputTuple,
      OrdersMatchedEvent.OutputObject
    >;
    OrdersMatched: TypedContractEvent<
      OrdersMatchedEvent.InputTuple,
      OrdersMatchedEvent.OutputTuple,
      OrdersMatchedEvent.OutputObject
    >;
  };
}
